### ISSUE TITLE
get banned issue

### ISSUE THREAD

**Issue by zcl826053242** [McDaived/NoRecoil-CS2#2]
did anyone get banned using such a tool ,pls let me know

**Comment by McDaived** [comment]
no it safe 99% you can check it here https://www.unknowncheats.me/forum/counter-strike-2-releases/600813-ahk-norecoil.html

**Comment by McDaived** [comment]
no it safe 99% you can check it here https://www.unknowncheats.me/forum/counter-strike-2-releases/600813-ahk-norecoil.html
