### ISSUE TITLE
CS2

### ISSUE THREAD

**Issue by hapvlz** [McDaived/NoRecoil-CS2#3]
Hey,

I've seen the title claims it support CS2, however do you have any video from testing?

Thanks for your work :)

**Comment by GentlemanMC** [comment]
the preview is literally cs2 

look at the hud

**Comment by McDaived** [comment]
> Hey,
> 
> I've seen the title claims it support CS2, however do you have any video from testing?
> 
> Thanks for your work :)

yes it support cs2 , when beta test deployed and it safe for now  100% without vac or red trust factor
