### ISSUE TITLE
NoRecoil not activating

### ISSUE THREAD

**Issue by n00bster-za** [McDaived/NoRecoil-CS2#8]
using AHK V1.1.13

changed binds to use function keys then entered my sens. Open up TDM game and the recoil is not working. What am I doing wrong

**Comment by McDaived** [comment]
delete and redownload noreoil and try again..

**Comment by n00bster-za** [comment]
this is a new download. only downloaded it now to test. does not work for me.

**Comment by azog6** [comment]
The script just doesn't work, not even editing the keys as I want, but it doesn't work. What may be the problem?

**Comment by McDaived** [comment]
i recommanded use ahk version 1.1.34.03

and download latest version of script from my github .. if still dosent work download old version of script from unkowncheats.
